// 该文件自动生成，请勿修改(除非知道自己在做什么)
/* eslint-disable */
export default {
  getBizParamsList: {
    url: '/bizParams/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postBizParamsUpdate: {
    url: '/bizParams/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postClassifyDelete: {
    url: '/classify/delete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getClassifyList: {
    url: '/classify/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postClassifySave: {
    url: '/classify/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postClassifyUpdate: {
    url: '/classify/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getClassifyPageExpertDetail: {
    url: '/classifyPage/expert/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getClassifyPageOfficialServiceDetail: {
    url: '/classifyPage/officialService/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getBrandList: {
    url: '/common/brand/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getCommonLocationList: {
    url: '/common/locationList',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getCommonQueryAreaList: {
    url: '/common/queryAreaList',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getCommonGroupList: {
    url: '/common/groupList',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getCommonOptions: {
    url: '/common/options',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getCommonReloadCache: {
    url: '/common/reloadCache',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postCommonSaveImage: {
    url: '/common/saveImage',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getConsultEntranceDetail: {
    url: '/consultEntrance/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getConsultEntranceQuery: {
    url: '/consultEntrance/query',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postConsultEntranceSave: {
    url: '/consultEntrance/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postConsultEntranceUpdate: {
    url: '/consultEntrance/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postConsultEntranceUpdateStatus: {
    url: '/consultEntrance/updateStatus',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postExpertDel: {
    url: '/expert/del',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getExpertDetail: {
    url: '/expert/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postExpertEdit: {
    url: '/expert/edit',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postExpertSave: {
    url: '/expert/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getExpertList: {
    url: '/expert/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postExpertServiceAudit: {
    url: '/expertService/audit',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postExpertServiceBatchDelete: {
    url: '/expertService/batchDelete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postExpertServiceBatchUpdatePriority: {
    url: '/expertService/batchUpdatePriority',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getExpertServiceDetail: {
    url: '/expertService/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getExpertServiceList: {
    url: '/expertService/list',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
  },
  getExpertServiceListForPriority: {
    url: '/expertService/listForPriority',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postExpertServiceSave: {
    url: '/expertService/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postExpertServiceUpdate: {
    url: '/expertService/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getGuidePageGetById: {
    url: '/guidePage/getById',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getGuidePageListByPage: {
    url: '/guidePage/listByPage',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postGuidePageRemove: {
    url: '/guidePage/remove',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postGuidePageSave: {
    url: '/guidePage/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postGuidePageUpdate: {
    url: '/guidePage/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getHomeDetail: {
    url: '/home/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postManualDelete: {
    url: '/interact/manual/delete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postManualInsert: {
    url: '/interact/manual/insert',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getManualList: {
    url: '/interact/manual/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postManualUpdate: {
    url: '/interact/manual/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postRobotDelete: {
    url: '/interact/robot/delete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postRobotInsert: {
    url: '/interact/robot/insert',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getRobotList: {
    url: '/interact/robot/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postRobotUpdate: {
    url: '/interact/robot/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getLandingPageDetail: {
    url: '/landingPage/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getLandingPageExpertDetail: {
    url: '/landingPage/expertDetail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getLandingPageOfficialServiceDetail: {
    url: '/landingPage/officialServiceDetail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getLandingPageQuery: {
    url: '/landingPage/query',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postLandingPageSave: {
    url: '/landingPage/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getLandingPageSimpleList: {
    url: '/landingPage/simpleList',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postLandingPageUpdate: {
    url: '/landingPage/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postOfficialServiceBatchDelete: {
    url: '/officialService/batchDelete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getOfficialServiceDetail: {
    url: '/officialService/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getOfficialServiceList: {
    url: '/officialService/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postOfficialServiceSave: {
    url: '/officialService/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postOfficialServiceUpdate: {
    url: '/officialService/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getLogExport: {
    url: '/robot/log/export',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getRobotWdList: {
    url: '/robot/wdList',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getLogList: {
    url: '/robot/log/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getRobotQuestionDetail: {
    url: '/robot/questionDetail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getRobotQuestionList: {
    url: '/robot/questionList',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postPolicyDelete: {
    url: '/route/policy/delete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getPolicyList: {
    url: '/route/policy/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getPolicyDetail: {
    url: '/route/policy/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postPolicySave: {
    url: '/route/policy/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postPolicyUpdate: {
    url: '/route/policy/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getRouteRuleChatTipDetail: {
    url: '/route/rule/chatTip/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postRuleDelete: {
    url: '/route/rule/delete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getRuleDetail: {
    url: '/route/rule/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getRouteRuleFeedbackDetail: {
    url: '/route/rule/feedback/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getRouteRuleInteractDetail: {
    url: '/route/rule/interact/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getRuleList: {
    url: '/route/rule/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postRuleSave: {
    url: '/route/rule/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postRouteRuleChatTipSave: {
    url: '/route/rule/chatTip/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postRouteRuleFeedbackSave: {
    url: '/route/rule/feedback/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postRouteRuleInteractSave: {
    url: '/route/rule/interact/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postWindowSave: {
    url: '/route/rule/window/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postRuleSort: {
    url: '/route/rule/sort',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postRuleUpdate: {
    url: '/route/rule/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getRouteRuleWindowDetail: {
    url: '/route/rule/window/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getChatTipDetail: {
    url: '/route/rule/global/chatTip/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getFeedbackDetail: {
    url: '/route/rule/global/feedback/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postFeedbackSave: {
    url: '/route/rule/global/feedback/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getInteractDetail: {
    url: '/route/rule/global/interact/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postInteractSave: {
    url: '/route/rule/global/interact/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postChatTipSave: {
    url: '/route/rule/global/chatTip/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getWindowDetail: {
    url: '/route/rule/global/window/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postRouteRuleGlobalWindowSave: {
    url: '/route/rule/global/window/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postSliderImageDelete: {
    url: '/sliderImage/delete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getSliderImageGet: {
    url: '/sliderImage/get',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postSliderImageSave: {
    url: '/sliderImage/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getSliderImageSearch: {
    url: '/sliderImage/search',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postSliderImageUpdate: {
    url: '/sliderImage/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getStatsFeedback: {
    url: '/stats/feedback',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postLandingPageClone: {
    url: '/landingPage/clone',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getForbidList: {
    url: '/forbid/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postForbidInsert: {
    url: '/forbid/insert',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postForbidUpdate: {
    url: '/forbid/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postForbidStatus: {
    url: '/forbid/status',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postToolConsultUrl: {
    url: '/tool/consultUrl',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getCommonOrgList: {
    url: '/common/orgList',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getUserCurrent: {
    url: '/user/current',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getUserFuzzy: {
    url: '/user/fuzzy',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postSpecialConsultBatchDelete: {
    url: '/specialConsult/batchDelete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getSpecialConsultDetail: {
    url: '/specialConsult/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getSpecialConsultList: {
    url: '/specialConsult/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postSpecialConsultSave: {
    url: '/specialConsult/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postSpecialConsultUpdate: {
    url: '/specialConsult/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postSpecialLocationDelete: {
    url: '/specialLocation/delete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getSpecialLocationDetail: {
    url: '/specialLocation/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getSpecialLocationList: {
    url: '/specialLocation/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postSpecialLocationSave: {
    url: '/specialLocation/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postSpecialLocationUpdate: {
    url: '/specialLocation/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getModuleList: {
    url: '/consult/module/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getSystemList: {
    url: '/consult/system/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postModuleSave: {
    url: '/consult/module/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postSystemSave: {
    url: '/consult/system/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postModuleUpdate: {
    url: '/consult/module/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postModuleDelete: {
    url: '/consult/module/delete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postSystemUpdate: {
    url: '/consult/system/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postSystemDelete: {
    url: '/consult/system/delete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postLocationCopy: {
    url: '/consult/location/copy',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postButtonDelete: {
    url: '/consult/button/delete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postLocationDelete: {
    url: '/consult/location/delete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getButtonDetail: {
    url: '/consult/button/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getButtonList: {
    url: '/consult/button/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getLocationDetail: {
    url: '/consult/location/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getLocationList: {
    url: '/consult/location/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getModuleDetail: {
    url: '/consult/module/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getSystemDetail: {
    url: '/consult/system/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postButtonSave: {
    url: '/consult/button/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postLocationSave: {
    url: '/consult/location/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postButtonUpdate: {
    url: '/consult/button/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postLocationUpdate: {
    url: '/consult/location/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getCommonQueryTag: {
    url: '/common/queryTag',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postPriorityDelete: {
    url: '/route/priority/delete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getPriorityDetail: {
    url: '/route/priority/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getPriorityList: {
    url: '/route/priority/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postPrioritySave: {
    url: '/route/priority/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postPriorityUpdate: {
    url: '/route/priority/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getConfigDetail: {
    url: '/appointment/config/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postConfigSave: {
    url: '/appointment/config/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getCommonOrgTree: {
    url: '/common/orgTree',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postChannelDelete: {
    url: '/promotion/channel/delete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getChannelDetail: {
    url: '/promotion/channel/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getChannelList: {
    url: '/promotion/channel/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postChannelSave: {
    url: '/promotion/channel/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postChannelUpdate: {
    url: '/promotion/channel/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getPromotionchannelDetail: {
    url: '/promotionchannel/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postPromotionchannelUpdate: {
    url: '/promotionchannel/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postPromotionchannelSave: {
    url: '/promotionchannel/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postPromotionchannelDelete: {
    url: '/promotionchannel/delete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getPromotionchannelList: {
    url: '/promotionchannel/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postModuleCopy: {
    url: '/consult/module/copy',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getCommonTest: {
    url: '/common/test',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getChannelExport: {
    url: '/promotion/channel/export',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getAuditList: {
    url: '/ask/question/audit/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postReplyAudit: {
    url: '/ask/reply/audit',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postReplyDelete: {
    url: '/ask/reply/delete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getQuestionReply: {
    url: '/ask/question/reply',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getQuestionList: {
    url: '/ask/question/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postReplySave: {
    url: '/ask/reply/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postRecommendUpdate: {
    url: '/ask/question/recommend/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postReplyUpdate: {
    url: '/ask/reply/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getTagTree: {
    url: '/common/tag/tree',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getQuestionDetail: {
    url: '/ask/question/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postEmpowerlevelDelete: {
    url: '/empowerlevel/delete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getEmpowerlevelDetail: {
    url: '/empowerlevel/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getEmpowerlevelList: {
    url: '/empowerlevel/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postEmpowerlevelSave: {
    url: '/empowerlevel/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postEmpowerlevelUpdate: {
    url: '/empowerlevel/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postUsertypeDelete: {
    url: '/usertype/delete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getUsertypeDetail: {
    url: '/usertype/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getUsertypeList: {
    url: '/usertype/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postUsertypeSave: {
    url: '/usertype/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postUsertypeUpdate: {
    url: '/usertype/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postUploadFile: {
    url: '/common/upload/file',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getRecordList: {
    url: '/ask/question/record/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getToolQueryLogList: {
    url: '/tool/queryLogList',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getCustomerList: {
    url: '/customer/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getProductdimensionList: {
    url: '/productdimension/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postProductdimensionUpdate: {
    url: '/productdimension/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getBrandListWalle: {
    url: '/brand/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postBrandUpdate: {
    url: '/brand/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getBrandtypeList: {
    url: '/brandtype/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postBrandtypeSave: {
    url: '/brandtype/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postBrandtypeUpdate: {
    url: '/brandtype/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postBusinesstypeDelete: {
    url: '/businesstype/delete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getBusinesstypeList: {
    url: '/businesstype/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getBusinesstypeSave: {
    url: '/businesstype/save',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postBrandtypeDelete: {
    url: '/brandtype/delete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getActionList: {
    url: '/operate/action/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postActionSave: {
    url: '/operate/action/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postActionUpdate: {
    url: '/operate/action/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postActionDelete: {
    url: '/operate/action/delete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getActionMatterList: {
    url: '/operate/action/matterList',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getRightDeductQuery: {
    url: '/rightDeduct/query',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getRightDeductDetail: {
    url: '/rightDeduct/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getDataList: {
    url: '/ask/question/data/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getVoteDownDetail: {
    url: '/ask/question/voteDown/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getQueueabandonLogExport: {
    url: '/queueabandon/log/export',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getQueueabandonLogList: {
    url: '/queueabandon/log/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getActionOption: {
    url: '/operate/action/option',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getPersonaConsultList: {
    url: '/dm/persona/consultList',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getPersonaList: {
    url: '/dm/persona/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getPersonaDetail: {
    url: '/dm/persona/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getConsultLastTagStatistics: {
    url: '/dm/consult/lastTagStatistics',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getConsultLocationStatistics: {
    url: '/dm/consult/locationStatistics',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getConsultMonthStatistics: {
    url: '/dm/consult/monthStatistics',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getConsultTagStatistics: {
    url: '/dm/consult/tagStatistics',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getPersonaTagStatistics: {
    url: '/dm/persona/tagStatistics',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getConsultGetYearTag: {
    url: '/dm/consult/getYearTag',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getExpertScheduleDetail: {
    url: '/expertSchedule/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postExpertScheduleImport: {
    url: '/expertSchedule/import',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'multipart/form-data' },
  },
  getExpertScheduleListByPage: {
    url: '/expertSchedule/listByPage',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getV2GetById: {
    url: '/guidePage/v2/getById',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postV2Save: {
    url: '/guidePage/v2/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postV2Update: {
    url: '/guidePage/v2/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getExpertInquiryRecordList: {
    url: '/expertInquiryRecord/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postExpertInquiryRecordComplete: {
    url: '/expertInquiryRecord/complete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postExpertInquiryRecordUpdateRecordContent: {
    url: '/expertInquiryRecord/updateRecordContent',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postCommonQueryClueRecord: {
    url: '/common/queryClueRecord',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postCommonSaveClueRecord: {
    url: '/common/saveClueRecord',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCommonQueryClueRecord: {
    url: '/common/queryClueRecord',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postExpertScheduleDetail: {
    url: '/expertSchedule/detail',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postExpertScheduleListByPage: {
    url: '/expertSchedule/listByPage',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postExpertInquiryRecordDealInquiryRecord: {
    url: '/expertInquiryRecord/dealInquiryRecord',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getExpertInquiryRecordListPage: {
    url: '/expertInquiryRecord/listPage',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getClueQueryClueRecord: {
    url: '/clue/queryClueRecord',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postClueSaveClueRecord: {
    url: '/clue/saveClueRecord',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getCommonDictValid: {
    url: '/common/dictValid',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getCustomerFuzzyQueryCompany: {
    url: '/customer/fuzzyQueryCompany',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getExpertInquiryRecordExport: {
    url: '/expertInquiryRecord/export',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getExpertInquiryRecordExpertList: {
    url: '/expertInquiryRecord/expertList',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getExpertInquiryRecordQueryExpertScheduleList: {
    url: '/expertInquiryRecord/queryExpertScheduleList',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postExpertInquiryRecordSaveInquiryRecord: {
    url: '/expertInquiryRecord/saveInquiryRecord',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postExpertScheduleDeleteInquirySchedule: {
    url: '/expertSchedule/deleteInquirySchedule',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getExpertScheduleQueryScheduleList: {
    url: '/expertSchedule/queryScheduleList',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getExpertScheduleQueryScheduleStatusList: {
    url: '/expertSchedule/queryScheduleStatusList',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postExpertScheduleSaveInquirySchedule: {
    url: '/expertSchedule/saveInquirySchedule',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getProductPackageList: {
    url: '/productPackage/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getProductPackageDetail: {
    url: '/productPackage/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postProductPackageOnShelf: {
    url: '/productPackage/onShelf',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postProductPackageSave: {
    url: '/productPackage/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postProductPackageUpdate: {
    url: '/productPackage/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getExpertScheduleQueryExpertScheduleList: {
    url: '/expertSchedule/queryExpertScheduleList',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getRightQueryCompanyRight: {
    url: '/right/queryCompanyRight',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getExpertScheduleGetScheduleByCodeList: {
    url: '/expertSchedule/getScheduleByCodeList',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getExpertPoolDetail: {
    url: '/expertPool/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getExpertPoolQuery: {
    url: '/expertPool/query',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postExpertPoolSave: {
    url: '/expertPool/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postExpertPoolUpdate: {
    url: '/expertPool/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getConfigQuery: {
    url: '/partCode/config/query',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postExpertPoolUpdateStatus: {
    url: '/expertPool/updateStatus',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getExpertPoolConfigQuery: {
    url: '/expertPool/config/query',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getExpertInquiryImportList: {
    url: '/expertInquiryImport/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getExpertInquiryImportGetImportTemplateUrl: {
    url: '/expertInquiryImport/getImportTemplateUrl',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postExpertInquiryImportBatchDeductRecord: {
    url: '/expertInquiryImport/batchDeductRecord',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postExpertInquiryImportNotDeductRecord: {
    url: '/expertInquiryImport/notDeductRecord',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postExpertInquiryImportImport: {
    url: '/expertInquiryImport/import',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCommonProperty: {
    url: '/common/property',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postExpertInquiryRecordUpdateCancelReason: {
    url: '/expertInquiryRecord/updateCancelReason',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postMarketActivityDelete: {
    url: '/marketActivity/delete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getMarketActivityList: {
    url: '/marketActivity/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postMarketActivityOnShelf: {
    url: '/marketActivity/onShelf',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getMarketActivityLogList: {
    url: '/marketActivityLog/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postMarketActivitySave: {
    url: '/marketActivity/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getTest: {
    url: '/test',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getGroupInfoList: {
    url: '/marketActivity/groupInfo/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getTestUploadFile: {
    url: '/test/uploadFile',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postServiceConfigSave: {
    url: '/serviceConfig/save',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postServiceConfigUpdate: {
    url: '/serviceConfig/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postServiceConfigDisable: {
    url: '/serviceConfig/disable',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getServiceConfigQuery: {
    url: '/serviceConfig/query',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getServiceConfigQueryScheduleStatusList: {
    url: '/serviceConfig/queryServiceConfigList',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postAdd: {
    url: '/consultRightConfig/add',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postDelete: {
    url: '/consultRightConfig/delete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postUpdate: {
    url: '/consultRightConfig/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getDetail: {
    url: '/consultRightConfig/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getListByPage: {
    url: '/consultRightConfig/listByPage',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getTestGetLoginUser: {
    url: '/test/getLoginUser',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getTestListByUserId: {
    url: '/test/listByUserId',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postServiceTimeBatchUpdate: {
    url: '/expertService/serviceTime/batchUpdate',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postServicelocationCheck: {
    url: '/expertService/serviceLocation/check',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getSelfserviceNoAnswerList: {
    url: '/selfservice/noAnswerList',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postBatchOperateCheckConfig: {
    url: '/route/rule/batchOperate/checkConfig',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postBatchOperateCopy: {
    url: '/route/rule/batchOperate/copy',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postBatchOperateUpdate: {
    url: '/route/rule/batchOperate/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getRuleCopy: {
    url: '/route/rule/copy',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postRuleList: {
    url: '/route/rule/list',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getExpertServiceExpertList: {
    url: '/expertService/expert/list',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCustomerQueryCompanyByName: {
    url: '/customer/queryCompanyByName',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getServiceConfigQueryIntentionServiceConfigList: {
    url: '/serviceConfig/queryIntentionServiceConfigList',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getSelfserviceErrorWarnList: {
    url: '/selfservice/errorWarnList',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postSelfserviceIgnoreErrorWarn: {
    url: '/selfservice/ignoreErrorWarn',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postSelfserviceRemoveIgnoreErrorWarn: {
    url: '/selfservice/removeIgnoreErrorWarn',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postFinancialTaxConfigAdd: {
    url: '/financialTaxConfig/add',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postFinancialTaxConfigDelete: {
    url: '/financialTaxConfig/delete',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postFinancialTaxConfigUpdate: {
    url: '/financialTaxConfig/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getFinancialTaxConfigDetail: {
    url: '/financialTaxConfig/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getFinancialTaxConfigListByPage: {
    url: '/financialTaxConfig/listByPage',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getFinancialTaxConfigSummary: {
    url: '/financialTaxConfig/summary',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postWarnConfigAdd: {
    url: '/warnConfig/add',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postWarnConfigUpdate: {
    url: '/warnConfig/update',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postWarnConfigBatchUpdateStatus: {
    url: '/warnConfig/batchUpdateStatus',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postWarnConfigBatchUpdate: {
    url: '/warnConfig/batchUpdate',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getWarnConfigDetail: {
    url: '/warnConfig/detail',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getWarnConfigListByPage: {
    url: '/warnConfig/listByPage',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  getCommonQueryGroupList: {
    url: '/common/queryGroupList',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
  },
  postPriorityBatchUpdate: {
    url: '/route/priority/batchUpdate',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postFeedbackBatchUpdate: {
    url: '/route/rule/feedback/batchUpdate',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postChatTipBatchUpdate: {
    url: '/route/rule/chatTip/batchUpdate',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postWindowBatchUpdate: {
    url: '/route/rule/window/batchUpdate',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postBatchUpdateCheckGlobalConfig: {
    url: '/route/rule/batchUpdate/checkGlobalConfig',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getRuleGetRouteRuleOptionConfigList: {
    url: '/route/rule/getRouteRuleOptionConfigList',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postSelfserviceImportExceptionTips: {
    url: '/selfservice/importExceptionTips',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'multipart/form-data' },
  },
  postSelfserviceImportHelpTips: {
    url: '/selfservice/importHelpTips',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'multipart/form-data' },
  },
  getSelfserviceGetImportHelpTipsTemplateUrl: {
    url: '/selfservice/getImportHelpTipsTemplateUrl',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getSelfserviceGetImportExceptionTipsTemplateUrl: {
    url: '/selfservice/getImportExceptionTipsTemplateUrl',
    method: 'get',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postForbidList: {
    url: '/forbid/list',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postWarnConfigListByPage: {
    url: '/warnConfig/listByPage',
    method: 'post',
    baseURL: '/yypt-olhelp-manage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
};
