// 该文件自动生成，请勿修改(除非知道自己在做什么)
/* eslint-disable */
export default {
  getServiceManageDetail: {
    url: '/andes/serviceManage/detail',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getBasecodeBxfyy: {
    url: '/comm/basecode/bxfyy',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getBasecodeDhJnz: {
    url: '/comm/basecode/dhJnz',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getBasecodeFzgs: {
    url: '/comm/basecode/fzgs',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getBasecodeFzgsForWdcx: {
    url: '/comm/basecode/fzgsForWdcx',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getBasecodeFzgsTree: {
    url: '/comm/basecode/fzgsTree',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getBasecodeGetlsqy: {
    url: '/comm/basecode/getlsqy',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getBasecodeRwlxByRwfs: {
    url: '/comm/basecode/rwlxByRwfs',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getBasecodeGetSswd: {
    url: '/comm/basecode/getSswd',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getBasecodeWd: {
    url: '/comm/basecode/wd',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getBasecodeGetWdBmByFzgsdm: {
    url: '/comm/basecode/getWdBmByFzgsdm',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getBasecodeWdForWdcx: {
    url: '/comm/basecode/wdForWdcx',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getBasecodeGetWdxxByDm: {
    url: '/comm/basecode/getWdxxByDm',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getBasecodeWmqyy: {
    url: '/comm/basecode/wmqyy',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getBasecodeXfyy: {
    url: '/comm/basecode/xfyy',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getBasecodeGetYhfkCpxl: {
    url: '/comm/basecode/getYhfkCpxl',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getBasecodeGetYhfkStatus: {
    url: '/comm/basecode/getYhfkStatus',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getBasecodeCpdlByFzgsdm: {
    url: '/comm/basecode/cpdlByFzgsdm',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getBasecodeQueryPzxxByJrhm: {
    url: '/comm/basecode/queryPzxxByJrhm',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getCommonAgentList: {
    url: '/common/agentList',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getLive800Permission: {
    url: '/common/live800/permission',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getFileDownload: {
    url: '/common/file/download',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCommonGroupList: {
    url: '/common/groupList',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCommonOrgTree: {
    url: '/common/orgTree',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCommonOptions: {
    url: '/common/options',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCommonReloadCache: {
    url: '/common/reloadCache',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  postZxglZxjl: {
    url: '/zxgl/zxjl',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getOlhelpChatList: {
    url: '/zxgl/olhelp/chatList',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getZxglGetExternalPlatformTelList: {
    url: '/zxgl/getExternalPlatformTelList',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getZxglKhxxList: {
    url: '/zxgl/khxxList',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getZxglLdzxList: {
    url: '/zxgl/ldzxList',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getTsxxGetOneYearTscs: {
    url: '/zxgl/tsxx/getOneYearTscs',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getZxglGetZxcs: {
    url: '/zxgl/getZxcs',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getTsxxTsxxCx: {
    url: '/zxgl/tsxx/tsxxCx',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getZxglQueryAreaidByZid: {
    url: '/zxgl/queryAreaidByZid',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getZxglQueryAreaList: {
    url: '/zxgl/queryAreaList',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getZxglQueryZxjlByLdhm: {
    url: '/zxgl/queryZxjlByLdhm',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  postZxglSendHdMessage: {
    url: '/zxgl/sendHdMessage',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getGroupList: {
    url: '/consultMatter/group/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  postPersonalSave: {
    url: '/consultMatter/personal/save',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getLxrGetLxrxxByYh: {
    url: '/customerCenter/lxr/getLxrxxByYh',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getNsdwGetNsdwByKhid: {
    url: '/customerCenter/nsdw/getNsdwByKhid',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCustomerCenterQueryCustomerInfoFromTaxNet: {
    url: '/customerCenter/queryCustomerInfoFromTaxNet',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getTemplateList: {
    url: '/email/template/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  postEmailSend: {
    url: '/email/send',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postYhfkAddYhfk: {
    url: '/yhfk/addYhfk',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getYhfkCheckYhfk: {
    url: '/yhfk/checkYhfk',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  postYhfkDeleteYhfk: {
    url: '/yhfk/deleteYhfk',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getYhfkQueryYhfkList: {
    url: '/yhfk/queryYhfkList',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  postYhfkUpdateYhfkZx: {
    url: '/yhfk/updateYhfkZx',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getFjShareFile: {
    url: '/other/fj/shareFile',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getGroupQueryGroupWorkFlag: {
    url: '/group/queryGroupWorkFlag',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getHsGetBindXzsInfo: {
    url: '/hs/getBindXzsInfo',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getSqxxGetFwsqByKhid: {
    url: '/auth/sqxx/getFwsqByKhid',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getSqxxGetRjsqByKhid: {
    url: '/auth/sqxx/getRjsqByKhid',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getOrderGetUserOrder: {
    url: '/sw/order/getUserOrder',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getCustomerPortalSearchCustomer: {
    url: '/customerPortal/searchCustomer',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getInternalDataDetail: {
    url: '/internalData/detail',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getInternalDataList: {
    url: '/internalData/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getYxxsGetWgbxsts: {
    url: '/yxgl/yxxs/getWgbxsts',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getYxxsDoingYxxsByYh: {
    url: '/yxgl/yxxs/doingYxxsByYh',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getYxxsXsDetail: {
    url: '/yxgl/yxxs/xsDetail',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getYxxsYxxsByYh: {
    url: '/yxgl/yxxs/yxxsByYh',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getRobotAsk: {
    url: '/olhelp/robot/ask',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getRobotDimension: {
    url: '/olhelp/robot/dimension',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getChatContent: {
    url: '/olhelp/chat/content',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getRobotSuggestedQuestion: {
    url: '/olhelp/robot/suggestedQuestion',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getPersonaQueryCustomerTagList: {
    url: '/persona/queryCustomerTagList',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getPersonaQueryPersonalTagList: {
    url: '/persona/queryPersonalTagList',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getToolDetail: {
    url: '/persona/tool/detail',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getCustomerJoinedList: {
    url: '/qq/group/customer/joinedList',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getCustomerRemainJoinList: {
    url: '/qq/group/customer/remainJoinList',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getPersonJoinedList: {
    url: '/qq/group/person/joinedList',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getCustomerQuery: {
    url: '/rights/consult/customer/query',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getCustomerList: {
    url: '/rights/train/customer/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getPersonQuery: {
    url: '/rights/consult/person/query',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getPersonList: {
    url: '/rights/train/person/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getSmsDxList: {
    url: '/sms/dxList',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  postSmsReSend: {
    url: '/sms/reSend',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postSmsDx: {
    url: '/sms/dx',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getSwFzgsSld: {
    url: '/sw/fzgsSld',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getSwHkzzUrl: {
    url: '/sw/hkzzUrl',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getSwYxtj: {
    url: '/sw/yxtj',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getSywPxjh: {
    url: '/syw/pxjh',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getDhrwCalloutList: {
    url: '/rwgl/dhrw/calloutList',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getRwglSmrwList: {
    url: '/rwgl/smrwList',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getRwglYcrwList: {
    url: '/rwgl/ycrwList',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getRwglZdxcList: {
    url: '/rwgl/zdxcList',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getUserCurrentUser: {
    url: '/user/currentUser',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getPermissionList: {
    url: '/user/permission/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getUserQueryByUserId: {
    url: '/user/queryByUserId',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  postAppealAppeal: {
    url: '/appeal/appeal',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getSmsMessageList: {
    url: '/sms/messageList',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postSmsReSendMessage: {
    url: '/sms/reSendMessage',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postSmsSendMessage: {
    url: '/sms/sendMessage',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getItpcoreGetBindInfo: {
    url: '/itpcore/getBindInfo',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getTrainGetEnrollUrl: {
    url: '/train/getEnrollUrl',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getOnlineList: {
    url: '/consult/record/online/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  postSuitSave: {
    url: '/suit/save',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getIncallList: {
    url: '/consult/record/incall/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getSuitList: {
    url: '/suit/suit/list',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getCalloutList: {
    url: '/task/callout/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getHomeList: {
    url: '/task/home/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getRemoteList: {
    url: '/task/remote/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getStoreList: {
    url: '/task/store/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  postClientRelationEnd: {
    url: '/agency/clientRelation/end',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getAgencyDetail: {
    url: '/agency/detail',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getAgencyList: {
    url: '/agency/list',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getAgencyQueryClient: {
    url: '/agency/queryClient',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postAgencyRemarkUpdate: {
    url: '/agency/remark/update',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getContactList: {
    url: '/company/contact/list',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCompanyList: {
    url: '/company/list',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCompanyQueryFromTaxNet: {
    url: '/company/queryFromTaxNet',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCompanyInfo: {
    url: '/company/info',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postRemarkUpdate: {
    url: '/company/remark/update',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getTagList: {
    url: '/company/tag/list',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postCompanyUnbindCompanyPerson: {
    url: '/company/unbindCompanyPerson',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getOrgList: {
    url: '/org/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getStationList: {
    url: '/org/station/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getOrgStoreList: {
    url: '/org/store/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getPersonalDetail: {
    url: '/personal/detail',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getPersonalQueryLastCallTime: {
    url: '/personal/queryLastCallTime',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postPersonalRemarkUpdate: {
    url: '/personal/remark/update',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getPersonalTagList: {
    url: '/personal/tag/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getGroupDetail: {
    url: '/group/detail',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getFileDownload_1604658160: {
    url: '/file/download',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  postFileUpload: {
    url: '/file/upload',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getClueList: {
    url: '/market/clue/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getClueCount: {
    url: '/market/clue/count',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getProductDue: {
    url: '/market/product/due',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getProductIntention: {
    url: '/market/product/intention',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  postClueSave: {
    url: '/market/clue/save',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getOrderList: {
    url: '/order/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getSendInvoiceModify: {
    url: '/sms/send/invoiceModify',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getClueList_1605681137: {
    url: '/clue/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getClueCount_1605681137: {
    url: '/clue/count',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getClueProductDue: {
    url: '/clue/product/due',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getClueProductIntention: {
    url: '/clue/product/intention',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postClueSave_1605681137: {
    url: '/clue/save',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postClueRenewIntention: {
    url: '/clue/renewIntention',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getSmsList: {
    url: '/sms/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  postSmsSend: {
    url: '/sms/send',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getRecordGetLastCallTime: {
    url: '/consult/record/getLastCallTime',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  postRecordSave: {
    url: '/consult/record/save',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getProductDueWalle: {
    url: '/product/due',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getProductIntentionWalle: {
    url: '/product/intention',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getConsultIncall: {
    url: '/consult/incall',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getCreditQuery: {
    url: '/personal/credit/query',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getRightsTrainCustomerQuery: {
    url: '/rights/train/customer/query',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getRightsTrainPersonQuery: {
    url: '/rights/train/person/query',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getClientList: {
    url: '/agency/client/list',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCompanySearch: {
    url: '/company/search',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getGroupListWalle: {
    url: '/group/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getV2List: {
    url: '/internalData/v2/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getIncallCount: {
    url: '/consult/incall/count',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getStoreCustomer: {
    url: '/org/store/customer',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getSuitCount: {
    url: '/suit/count',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getOrgTree: {
    url: '/org/tree',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getSmsTemplate: {
    url: '/sms/template',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getClassifyList: {
    url: '/product/classify/list',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getTaskQueryType: {
    url: '/task/queryType',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getUserFuzzyQuery: {
    url: '/user/fuzzyQuery',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getMarketDivideList: {
    url: '/customer/marketDivide/list',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getCompanyToolDetail: {
    url: '/company/tool/detail',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getFileShareFile: {
    url: '/file/shareFile',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getCommonQueryAreaList: {
    url: '/common/queryAreaList',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getTypeList: {
    url: '/task/type/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  postTaskRemindCallback: {
    url: '/task/remindCallback',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getCompanyStore: {
    url: '/company/store',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getSuitList_1606819251: {
    url: '/suit/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getBankCollection: {
    url: '/bank/collection',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getOrderLogistics: {
    url: '/order/logistics',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  postSendInvoiceModify: {
    url: '/sms/send/invoiceModify',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getRecordDetail: {
    url: '/consult/online/record/detail',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getActionList: {
    url: '/operate/action/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  postActionSave: {
    url: '/operate/action/save',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getActionDetailList: {
    url: '/operate/action/detailList',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getAgencyQuery: {
    url: '/rights/consult/agency/query',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getAgencySearch: {
    url: '/agency/search',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getAgencyAgentInfo: {
    url: '/agency/agentInfo',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getAgencyTagList: {
    url: '/agency/tag/list',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postCommonFileUpload: {
    url: '/common/file/upload',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'multipart/form-data' },
  },
  postServiceAccept: {
    url: '/special/service/accept',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getServiceList: {
    url: '/special/service/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  postServiceSendMessage: {
    url: '/special/service/sendMessage',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postServiceClose: {
    url: '/special/service/close',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postProcessFinish: {
    url: '/special/service/process/finish',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getConsultList: {
    url: '/special/service/consult/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  postCommunicationSave: {
    url: '/special/service/communication/save',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postServiceUploadFile: {
    url: '/special/service/uploadFile',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCustomerCenterQueryCompanyInfo: {
    url: '/customerCenter/queryCompanyInfo',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postServiceDeleteAttachment: {
    url: '/special/service/deleteAttachment',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postServiceCalculateRealTaxBurdenRate: {
    url: '/special/service/calculateRealTaxBurdenRate',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getTableDetail: {
    url: '/special/service/table/detail',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getServiceDetail: {
    url: '/special/service/detail',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getTreeMonth: {
    url: '/special/service/tree/month',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getTreeTable: {
    url: '/special/service/tree/table',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getServiceDetailByLogId: {
    url: '/special/service/detailByLogId',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getServiceDetailByProcessRecordId: {
    url: '/special/service/detailByProcessRecordId',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getServiceDetailByRecordId: {
    url: '/special/service/detailByRecordId',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getServiceDetailForEp: {
    url: '/special/service/detailForEp',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  postServiceRealTaxBurdenRate: {
    url: '/special/service/realTaxBurdenRate',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getCustomerDetail: {
    url: '/rights/consult/customer/detail',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getTodoTaskUploadTodoReportData: {
    url: '/todoTask/uploadTodoReportData',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getTodoTaskConsultTodoQuery: {
    url: '/todoTask/consultTodoQuery',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getRelList: {
    url: '/company/rel/list',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getQuestionnaireCompanyList: {
    url: '/questionnaire/company/list',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  getAgentPermissionSyntheticalPage_1668155970: {
    url: '/agentPermission/syntheticalPage',
    method: 'get',
    baseURL: '/callcenterweb',
  },
  postQuestionnaireGetUrl: {
    url: '/questionnaire/getUrl',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postAiAnalyze: {
    url: '/consult/oline/record/ai/analyze',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getMaterialGetMaterial: {
    url: '/material/getMaterial',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getSmsQueryTemplateList: {
    url: '/sms/queryTemplateList',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getSmsGetTemplateContent: {
    url: '/sms/getTemplateContent',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getOrderNewList: {
    url: '/order/newList',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCommonTest: {
    url: '/common/test',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postWorkOrderCreate: {
    url: '/isd/workOrder/create',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postWorkOrderEdit: {
    url: '/isd/workOrder/edit',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getWorkOrderPageList: {
    url: '/isd/workOrder/pageList',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getPageListTeam: {
    url: '/isd/workOrder/pageList/team',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getPageListManage: {
    url: '/isd/workOrder/pageList/manage',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getDetailTeam: {
    url: '/isd/workOrder/detail/team',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getDetailMange: {
    url: '/isd/workOrder/detail/mange',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getDetailUser: {
    url: '/isd/workOrder/detail/user',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postWorkOrderBatchCloseOrder: {
    url: '/isd/workOrder/batchCloseOrder',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postWorkOrderHandleOrder: {
    url: '/isd/workOrder/handleOrder',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postWorkOrderSolveOrder: {
    url: '/isd/workOrder/solveOrder',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postWorkOrderUpgradeStopPage: {
    url: '/isd/workOrder/upgradeStopPage',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postWorkOrderSycStopPage: {
    url: '/isd/workOrder/sycStopPage',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postCommonGetJsapiSignature: {
    url: '/common/getJsapiSignature',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getWorkOrderQuestionLabelDict: {
    url: '/isd/workOrder/questionLabelDict',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getWorkOrderGetZentaoModule: {
    url: '/isd/workOrder/getZentaoModule',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCommonOrderOptions: {
    url: '/common/orderOptions',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getConfigGetLatestSpecialServiceConfig: {
    url: '/special/service/config/getLatestSpecialServiceConfig',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postServiceUploadWealthAndAccountAttachment: {
    url: '/special/service/uploadWealthAndAccountAttachment',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postServiceAddSpecialServiceRecord: {
    url: '/special/service/addSpecialServiceRecord',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getSchedulePageList: {
    url: '/specialService/schedule/pageList',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getServiceQueryWealthAccountInfo: {
    url: '/special/service/queryWealthAccountInfo',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getScheduleTaskDetail: {
    url: '/specialService/schedule/taskDetail',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postScheduleUpdateSubTaskStatus: {
    url: '/specialService/schedule/updateSubTaskStatus',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postScheduleUpdateSubTaskMatterStatus: {
    url: '/specialService/schedule/updateSubTaskMatterStatus',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postScheduleDelFeedbackFile: {
    url: '/specialService/schedule/delFeedbackFile',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postSubTaskSave: {
    url: '/special/service/execPlan/subTask/save',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postServiceDetection: {
    url: '/special/service/detection',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postServiceUpdateDetection: {
    url: '/special/service/updateDetection',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postServiceSelectInterrogation: {
    url: '/special/service/selectInterrogation',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postServiceUpdateInterrogation: {
    url: '/special/service/updateInterrogation',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getPlanGetRequirementList: {
    url: '/special/service/plan/getRequirementList',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getPlanGetSolutionList: {
    url: '/special/service/plan/getSolutionList',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getPlanGetTaskList: {
    url: '/special/service/plan/getTaskList',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getServiceGetRecordMaterialList: {
    url: '/special/service/getRecordMaterialList',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postExecPlanDelete: {
    url: '/special/service/execPlan/delete',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postSubTaskDelete: {
    url: '/special/service/execPlan/subTask/delete',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postSubTaskUpdate: {
    url: '/special/service/execPlan/subTask/update',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postExecMatterSave: {
    url: '/special/service/execPlan/execMatter/save',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postExecMatterDelete: {
    url: '/special/service/execPlan/execMatter/delete',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getDeletedRequirementAndSolutionQuery: {
    url: '/special/service/execPlan/deletedRequirementAndSolution/query',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getExecPlanQuery: {
    url: '/special/service/execPlan/query',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postPlanSelect: {
    url: '/special/service/plan/select',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getSchemeGenerate: {
    url: '/special/service/scheme/generate',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postPlanUpdateMaterial: {
    url: '/special/service/plan/updateMaterial',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postExecPlanSave: {
    url: '/special/service/execPlan/save',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postServiceUploadFileAndUpdateBusiness: {
    url: '/special/service/uploadFileAndUpdateBusiness',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postSchemePublish: {
    url: '/special/service/scheme/publish',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getServiceCheckExistRecord: {
    url: '/special/service/checkExistRecord',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postServiceAddPreSale: {
    url: '/special/service/addPreSale',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postExecPlanExcelExport: {
    url: '/special/service/execPlanExcel/export',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postSchemeWordExport: {
    url: '/special/service/schemeWord/export',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postServiceUploadRecordMaterial: {
    url: '/special/service/uploadRecordMaterial',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postServiceDeleteRecordMaterial: {
    url: '/special/service/deleteRecordMaterial',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postWorkOrderCancelOrderSolve: {
    url: '/isd/workOrder/cancelOrderSolve',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postWorkOrderCacheSolveOrderData: {
    url: '/isd/workOrder/cacheSolveOrderData',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getWorkOrderGetCacheSolveOrderData: {
    url: '/isd/workOrder/getCacheSolveOrderData',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getDeleteCheck: {
    url: '/special/service/execPlan/execMatter/delete/check',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getOlAgentAssistanceGetAnswer: {
    url: '/olAgentAssistance/getAnswer',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCommonGetIrisValue: {
    url: '/common/getIrisValue',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getManageExport: {
    url: '/isd/workOrder/pageList/manage/export',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getTeamExport: {
    url: '/isd/workOrder/pageList/team/export',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postServiceAccountBalance: {
    url: '/special/service/accountBalance',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getWorkOrderGetOperator: {
    url: '/isd/workOrder/getOperator',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postFeedbackSave: {
    url: '/isd/workOrder/solution/feedback/save',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postFrontEndConfigSave: {
    url: '/frontEndConfig/save',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getFrontEndConfigQuery: {
    url: '/frontEndConfig/query',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getModelButtonQuery: {
    url: '/olAgentAssistance/modelButton/query',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getServiceZxCompanySearch: {
    url: '/special/service/zxCompanySearch',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postServiceSaveZXPTPreSale: {
    url: '/special/service/saveZXPTPreSale',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getUserFuzzyQueryOnJob: {
    url: '/user/fuzzyQueryOnJob',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postWorkOrderUploadAndSendMegCard: {
    url: '/isd/workOrder/uploadAndSendMegCard',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postScheduleHistorySave: {
    url: '/special/service/scheduleHistory/save',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postWorkOrderReassign: {
    url: '/isd/workOrder/reassign',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postDescriptionRemind: {
    url: '/isd/workOrder/additional/description/remind',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postDescriptionSave: {
    url: '/isd/workOrder/additional/description/save',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postReportDetection: {
    url: '/special/service/tax/report/detection',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getServiceGetMaterialRecordList: {
    url: '/special/service/getMaterialRecordList',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postServiceOperationMaterialRecordStatus: {
    url: '/special/service/operationMaterialRecordStatus',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postServiceUpdateMaterialRecord: {
    url: '/special/service/updateMaterialRecord',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postServiceSaveCustomMaterialRecord: {
    url: '/special/service/saveCustomMaterialRecord',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postServiceUpdateCustomMaterialRecord: {
    url: '/special/service/updateCustomMaterialRecord',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postServiceDeleteCustomMaterialRecord: {
    url: '/special/service/deleteCustomMaterialRecord',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postServiceUpdatePublishStatus: {
    url: '/special/service/updatePublishStatus',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postServiceCheckPreSale: {
    url: '/special/service/checkPreSale',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postMarkRead: {
    url: '/isd/workOrder/additional/description/mark/read',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postWorkOrderUploadAndSendMsgCard: {
    url: '/isd/workOrder/uploadAndSendMsgCard',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getCommonHierarchicalOptions: {
    url: '/common/hierarchicalOptions',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postServiceQueryTable: {
    url: '/special/service/queryTable',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getFileWriteStream: {
    url: '/file/writeStream',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getWorkOrderConversionZenTaoUrl: {
    url: '/isd/workOrder/conversionZenTaoUrl',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getScheduleHistoryList: {
    url: '/special/service/scheduleHistory/list',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCompanyQueryCustomerId: {
    url: '/company/queryCustomerId',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getAccessLogQueryByLogId: {
    url: '/accessLog/queryByLogId',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postServiceAddEarlySpecialService: {
    url: '/special/service/addEarlySpecialService',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postDeliveryDashboard: {
    url: '/special/service/delivery/dashboard',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postDashboardExport: {
    url: '/special/service/delivery/dashboard/export',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postServicePeriodicServiceReport: {
    url: '/special/service/periodicServiceReport',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postPreDetection: {
    url: '/special/service/pre/detection',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postExcelTask: {
    url: '/common/excel/task',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postServiceEditRoleRecord: {
    url: '/special/service/editRoleRecord',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getServiceQueryRoleRecord: {
    url: '/special/service/queryRoleRecord',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postWorkOrderGetSecuritySign: {
    url: '/isd/workOrder/getSecuritySign',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getOlAgentAssistanceFactorsDict: {
    url: '/olAgentAssistance/factorsDict',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getOlAgentAssistanceGetQuestionReply: {
    url: '/olAgentAssistance/getQuestionReply',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getWorkOrderGetProductList: {
    url: '/isd/workOrder/getProductCategoryList',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getLatestScheduleQuery: {
    url: '/special/service/scheduleHistory/latestSchedule/query',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postMsgTest: {
    url: '/isd/workOrder/msg/test',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postCommonGetSecuritySign: {
    url: '/common/getSecuritySign',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getTaxDeclare: {
    url: '/thirdService/tax/declare',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getOlAgentAssistanceGetFactorDict: {
    url: '/olAgentAssistance/getFactorDict',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postExceptionSave: {
    url: '/isd/exception/save',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postExceptionUpdate: {
    url: '/isd/exception/update',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postStatusUpdate: {
    url: '/isd/exception/status/update',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getExceptionDetail: {
    url: '/isd/exception/detail',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postExceptionDelete: {
    url: '/isd/exception/delete',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postExceptionPage: {
    url: '/isd/exception/page',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getServiceCheckExistSpecialServiceTable: {
    url: '/special/service/checkExistSpecialServiceTable',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postServiceUpdateSpecialServiceTable: {
    url: '/special/service/updateSpecialServiceTable',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getServiceGetServiceSendBack: {
    url: '/special/service/getServiceSendBack',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postUniqueCheck: {
    url: '/isd/exception/unique/check',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postExceptionFollow: {
    url: '/isd/exception/follow',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getServiceQuestion: {
    url: '/isd/self/service/question',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getServiceGetAnswer: {
    url: '/isd/self/service/getAnswer',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postServicePreGetAnswer: {
    url: '/isd/self/service/preGetAnswer',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postFactorClear: {
    url: '/olAgentAssistance/factor/clear',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getServiceHasCreateWorkOrder: {
    url: '/isd/self/service/hasCreateWorkOrder',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postServiceVote: {
    url: '/isd/self/service/vote',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getServiceQueryVote: {
    url: '/isd/self/service/queryVote',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getSystemAndModuleQuery: {
    url: '/isd/self/service/systemAndModule/query',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getLocationQuery: {
    url: '/isd/self/service/search/page/location/query',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postCarbonCopyUserSet: {
    url: '/isd/workOrder/carbonCopyUser/set',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postAnswerList: {
    url: '/olAgentAssistance/history/answer/list',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postAnswerSend: {
    url: '/olAgentAssistance/history/answer/send',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postAnswerType: {
    url: '/olAgentAssistance/history/answer/type',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postViewLast: {
    url: '/olAgentAssistance/history/answer/view/last',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postViewSave: {
    url: '/olAgentAssistance/history/answer/view/save',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getChatAnalysisResultDetail: {
    url: '/isd/chatAnalysisResult/detail',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postChatAnalysisResultPage: {
    url: '/isd/chatAnalysisResult/follow',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postManageCancelDeliverySchedule: {
    url: '/expert/schedule/manage/cancelDeliverySchedule',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getManageDeliveryScheduleDetail: {
    url: '/expert/schedule/manage/deliveryScheduleDetail',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getManageDetail: {
    url: '/expert/schedule/manage/detail',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postManageExpertScheduleAppointment: {
    url: '/expert/schedule/manage/expertScheduleAppointment',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getManageGetDeliveryScheduleList: {
    url: '/expert/schedule/manage/queryDeliveryScheduleList',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postManageOperationServiceExpert: {
    url: '/expert/schedule/manage/operationServiceExpert',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getCommonClassifyList: {
    url: '/common/classify/list',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getManageCustomerScheduleRecordPage: {
    url: '/expert/schedule/manage/customerScheduleRecordPage',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postManageBatchCloseProject: {
    url: '/expert/schedule/manage/batchCloseProject',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postManageBatchStartProject: {
    url: '/expert/schedule/manage/batchStartProject',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postManageUpdateDeliverySchedule: {
    url: '/expert/schedule/manage/updateDeliverySchedule',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postManageReplaceDeliverySchedule: {
    url: '/expert/schedule/manage/replaceDeliverySchedule',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postManageSaveDeliverySchedule: {
    url: '/expert/schedule/manage/saveDeliverySchedule',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postRecordPage: {
    url: '/expert/schedule/manage/un/schedule/record/page',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postEditRemark: {
    url: '/expert/schedule/manage/un/schedule/record/edit/remark',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postEditRole: {
    url: '/expert/schedule/manage/un/schedule/record/edit/role',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postEditSchedule: {
    url: '/expert/schedule/manage/un/schedule/record/edit/schedule',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getCustomerInfoQuery: {
    url: '/isd/chatAnalysisResult/customerInfo/query',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postManageExpertPageList: {
    url: '/expert/schedule/manage/expertPageList',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getExpertScheduleManageGetDeliveryScheduleList: {
    url: '/expert/schedule/manage/getDeliveryScheduleList',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getManageQueryProjectSimpleInfo: {
    url: '/expert/schedule/manage/queryProjectSimpleInfo',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getManageQueryPlanSimpleInfo: {
    url: '/expert/schedule/manage/queryPlanSimpleInfo',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postManageCustomerScheduleRecordPage: {
    url: '/expert/schedule/manage/customerScheduleRecordPage',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postIsdChatAnalysisResultPage: {
    url: '/isd/chatAnalysisResult/page',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getScheduleMsg: {
    url: '/expert/schedule/manage/un/schedule/msg',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postServiceSave: {
    url: '/isd/self/service/save',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getExceptionExceptionStatistic: {
    url: '/isd/exception/exceptionStatistic',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postOlAgentAssistanceAnalyzeChat: {
    url: '/olAgentAssistance/analyzeChat',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getOlAgentAssistanceChatAnalyzeResultList: {
    url: '/olAgentAssistance/chatAnalyzeResultList',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postOlAgentAssistanceCacheAuoCoverFlag: {
    url: '/olAgentAssistance/cacheAuoCoverFlag',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postExpertCount: {
    url: '/expert/schedule/manage/un/schedule/batch/expert/count',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postMarkDivide: {
    url: '/expert/schedule/manage/mark/divide',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postExpertScheduleManageUnScheduleBatchPreExpertSchedule: {
    url: '/expert/schedule/manage/un/schedule/batch/pre/expert/schedule',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postSearchCustomer: {
    url: '/expert/schedule/manage/un/schedule/batch/expert/search/customer',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postManageBatchNoDelivery: {
    url: '/expert/schedule/manage/batchNoDelivery',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postManageCancelNoDelivery: {
    url: '/expert/schedule/manage/cancelNoDelivery',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postAnswerView: {
    url: '/olAgentAssistance/knowledge/history/answer/view',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postOlAgentAssistanceKnowledgeHistoryAnswerViewSave: {
    url: '/olAgentAssistance/knowledge/history/answer/view/save',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getRecordList: {
    url: '/consult/record/list',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getBusinessMsg: {
    url: '/expert/schedule/manage/self/business/msg',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postSearchExpert: {
    url: '/expert/schedule/manage/un/schedule/batch/expert/search/expert',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getCommonQueryOptionsSort: {
    url: '/common/queryOptionsSort',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getManageExecuteExpertScheduleStatusData: {
    url: '/expert/schedule/manage/executeExpertScheduleStatusData',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postManageBatchCancelSchedule: {
    url: '/expert/schedule/manage/batchCancelSchedule',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postDraftScheduleRecordPage: {
    url: '/expert/schedule/manage/customer/draftScheduleRecord/page',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postPapersScheduleRecordPage: {
    url: '/expert/schedule/manage/customer/papersScheduleRecord/page',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postManageSaveExpertCustomerSchedule: {
    url: '/expert/schedule/manage/saveExpertCustomerSchedule',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getManageCheckExistSchedule: {
    url: '/expert/schedule/manage/checkExistSchedule',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getTaxCategoryCodeQueryTaxCategoryCode: {
    url: '/taxCategoryCode/queryTaxCategoryCode',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postConsulttaskruletodoOnlineCreateTodo: {
    url: '/consulttaskruletodo/online/create/todo',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postConsulttaskruletodoIncallCreateTodo: {
    url: '/consulttaskruletodo/incall/create/todo',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postConsulttaskruletodoCallbackCreateTodo: {
    url: '/consulttaskruletodo/callback/create/todo',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postAutoList: {
    url: '/olAgentAssistance/knowledge/history/answer/auto/list',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postConsulttaskruletodoOutCreateTodo: {
    url: '/consulttaskruletodo/out/create/todo',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postVoiceGetOlVoice2Text: {
    url: '/voice/getOlVoice2Text',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getAgencySearchNonCloudAgency: {
    url: '/agency/searchNonCloudAgency',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postCompanyCheckTemporaryCompanyConfig: {
    url: '/company/checkTemporaryCompanyConfig',
    method: 'post',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getCustomerCenterSearchRegionCustomerByContent: {
    url: '/customerCenter/searchRegionCustomerByContent',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCommonQueryLocationCode: {
    url: '/common/queryLocationCode',
    method: 'get',
    baseURL: '/callcenterweb',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
};
