// 该文件自动生成，请勿修改(除非知道自己在做什么)
/* eslint-disable */
export default {
  postAgentBatchDeleteGroupRelation: {
    url: '/agent/batchDeleteGroupRelation',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postAgentBatchSaveGroupRelation: {
    url: '/agent/batchSaveGroupRelation',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postAgentBatchUpdateGroupPriority: {
    url: '/agent/batchUpdateGroupPriority',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postAgentBatchUpdateGroupRelation: {
    url: '/agent/batchUpdateGroupRelation',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postAgentBatchUpdateMainGroup: {
    url: '/agent/batchUpdateMainGroup',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postAgentBatchUpdateMaxReception: {
    url: '/agent/batchUpdateMaxReception',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getAgentDetail: {
    url: '/agent/detail',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getAgentList: {
    url: '/agent/list',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getAgentListGroupRalation: {
    url: '/agent/listGroupRalation',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getAgentListGroupPriority: {
    url: '/agent/listGroupPriority',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getAgentListMainGroup: {
    url: '/agent/listMainGroup',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postAgentUpdate: {
    url: '/agent/update',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postAgentUpdateGroupPriority: {
    url: '/agent/updateGroupPriority',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postBlackListBatchDelete: {
    url: '/blackList/batchDelete',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getBlackListList: {
    url: '/blackList/list',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postBlackListSave: {
    url: '/blackList/save',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postBlackListUpdate: {
    url: '/blackList/update',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getFileDownload: {
    url: '/common/file/download',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCommonGetSkillGroupList: {
    url: '/common/getSkillGroupList',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCommonGetWorkGroupList: {
    url: '/common/getWorkGroupList',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCommonListGroup: {
    url: '/common/listGroup',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCommonAreaList: {
    url: '/common/areaList',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCommonOptions: {
    url: '/common/options',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCommonReloadCache: {
    url: '/common/reloadCache',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postUploadFile: {
    url: '/common/upload/file',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'multipart/form-data' },
  },
  postContentDelete: {
    url: '/consultMatter/content/delete',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postConsultMatterGroupDelete: {
    url: '/consultMatter/group/delete',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postPersonalDelete: {
    url: '/consultMatter/personal/delete',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getGroupList: {
    url: '/consultMatter/group/list',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getPersonalList: {
    url: '/consultMatter/personal/list',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postContentSave: {
    url: '/consultMatter/content/save',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postConsultMatterGroupSave: {
    url: '/consultMatter/group/save',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postContentUpdate: {
    url: '/consultMatter/content/update',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postConsultMatterGroupUpdate: {
    url: '/consultMatter/group/update',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postTemplateDelete: {
    url: '/email/template/delete',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getTemplateDetail: {
    url: '/email/template/detail',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getTemplateList: {
    url: '/email/template/list',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postTemplateSave: {
    url: '/email/template/save',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postTemplateUpdate: {
    url: '/email/template/update',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postExtNumberBatchDelete: {
    url: '/extNumber/batchDelete',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getExtNumberList: {
    url: '/extNumber/list',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postExtNumberSave: {
    url: '/extNumber/save',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postExtNumberUpdate: {
    url: '/extNumber/update',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postGroupDelete: {
    url: '/group/delete',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postGroupEnable: {
    url: '/group/enable',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getIncallDetail: {
    url: '/group/incall/detail',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getIncallList: {
    url: '/group/incall/list',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getOnlineDetail: {
    url: '/group/online/detail',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getOnlineList: {
    url: '/group/online/list',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postGroupSave: {
    url: '/group/save',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postGroupUpdate: {
    url: '/group/update',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postInternalDataDelete: {
    url: '/internalData/delete',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getInternalDataDetail: {
    url: '/internalData/detail',
    method: 'get',
    baseURL: '/callcentermanage',
  },
  getInternalDataList: {
    url: '/internalData/list',
    method: 'get',
    baseURL: '/callcentermanage',
  },
  postInternalDataSave: {
    url: '/internalData/save',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getCallGetOperatorCallDetail: {
    url: '/monitor/call/getOperatorCallDetail',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCallGetSkillGroupResourceDetail: {
    url: '/monitor/call/getSkillGroupResourceDetail',
    method: 'get',
    baseURL: '/callcentermanage',
  },
  getOrgCompanyList: {
    url: '/org/companyList',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getOrgDepartmentList: {
    url: '/org/departmentList',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getOrgTree: {
    url: '/org/tree',
    method: 'get',
    baseURL: '/callcentermanage',
  },
  postSpecialDayBatchDelete: {
    url: '/specialDay/batchDelete',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postSpecialDayBatchUpdate: {
    url: '/specialDay/batchUpdate',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getSpecialDayList: {
    url: '/specialDay/list',
    method: 'get',
    baseURL: '/callcentermanage',
  },
  postSpecialDaySave: {
    url: '/specialDay/save',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getUserCurrentUser: {
    url: '/user/currentUser',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getUserFuzzyQuery: {
    url: '/user/fuzzyQuery',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postWorkTimeBatchDelete: {
    url: '/workTime/batchDelete',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postWorkTimeBatchUpdate: {
    url: '/workTime/batchUpdate',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getWorkTimeList: {
    url: '/workTime/list',
    method: 'get',
    baseURL: '/callcentermanage',
  },
  postWorkTimeSave: {
    url: '/workTime/save',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postContentSort: {
    url: '/consultMatter/content/sort',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postGroupSort: {
    url: '/consultMatter/group/sort',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getGroupList1: {
    url: '/consultMatter/group/list1',
    method: 'get',
    baseURL: '/callcentermanage',
  },
  getGroupList2: {
    url: '/consultMatter/group/list2',
    method: 'get',
    baseURL: '/callcentermanage',
  },
  getConfigDetail: {
    url: '/specialservice/config/detail',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postConfigSave: {
    url: '/specialservice/config/save',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postConfigUpdate: {
    url: '/specialservice/config/update',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getConfigList: {
    url: '/special/service/config/list',
    method: 'get',
    baseURL: '/callcentermanage',
  },
  getSpecialserviceConfigList: {
    url: '/specialservice/config/list',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getProcessDefine: {
    url: '/specialservice/config/process/define',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postAttachmentUpload: {
    url: '/specialservice/config/attachment/upload',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'multipart/form-data' },
  },
  postConfigUpdateStatus: {
    url: '/specialservice/config/updateStatus',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postAgentBatchUpdateAutoAllocation: {
    url: '/agent/batchUpdateAutoAllocation',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postWorkTimeBatchUpdateSameWorkTime: {
    url: '/workTime/batchUpdateSameWorkTime',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getWorkTimeQuerySameWorkTime: {
    url: '/workTime/querySameWorkTime',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCommonTest: {
    url: '/common/test',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postGlobalConfigSave: {
    url: '/group/callCompletingRateAlarm/globalConfig/save',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getTT: {
    url: '/t/t',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getGroupCallCompletingRateAlarmGlobalConfigDetail: {
    url: '/group/callCompletingRateAlarm/globalConfig/detail',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postResourcePoolDelete: {
    url: '/resourcePool/delete',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postResourcePoolDetail: {
    url: '/resourcePool/detail',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postResourcePoolInsert: {
    url: '/resourcePool/insert',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postResourcePoolPage: {
    url: '/resourcePool/page',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postResourcePoolUpdate: {
    url: '/resourcePool/update',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getCommonQueryGroupList: {
    url: '/common/queryGroupList',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getClassifyList: {
    url: '/classify/list',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postIsdConfigPage: {
    url: '/isdConfig/update',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getSystemAndModuleQuery: {
    url: '/isdConfig/systemAndModule/query',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postIsdConfigPage_1705483209: {
    url: '/isdConfig/page',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getCancelPublish: {
    url: '/smart/chat/analysis/plan/cancel/publish',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postPlanPage: {
    url: '/smart/chat/analysis/plan/page',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getPlanPublish: {
    url: '/smart/chat/analysis/plan/publish',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postRuleSave: {
    url: '/smart/chat/analysis/plan/rule/save',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postTargetSave: {
    url: '/smart/chat/analysis/plan/target/save',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getPlanDetail: {
    url: '/smart/chat/analysis/plan/detail',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getTargetDetail: {
    url: '/smart/chat/analysis/plan/target/detail',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postPlanPreview: {
    url: '/smart/chat/analysis/plan/preview',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getPlanTest: {
    url: '/smart/chat/analysis/plan/test',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getPlanConfig: {
    url: '/smart/chat/analysis/plan/config',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postSmartChatAnalysisTaskSave: {
    url: '/smartChatAnalysisTask/save',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getSmartChatAnalysisTaskPage: {
    url: '/smartChatAnalysisTask/page',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getTeamExport: {
    url: '/smartChatAnalysisTask/task/export',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCommonDimensionList: {
    url: '/common/dimensionList',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getSystemParamsQuery: {
    url: '/systemParams/query',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postSystemParamsSave: {
    url: '/systemParams/save',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getPreviewSnapshot: {
    url: '/smart/chat/analysis/plan/preview/snapshot',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getConfigRule: {
    url: '/smart/chat/analysis/plan/config/rule',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getPermissionList: {
    url: '/permission/list',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getPlanMessage: {
    url: '/smart/chat/analysis/plan/message',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getPlanGetFmtAnswer: {
    url: '/smart/chat/analysis/plan/getFmtAnswer',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCommonTestQQt: {
    url: '/common/testQQt',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCommonTest1: {
    url: '/common/test1',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postIsdConfigBatchDelete: {
    url: '/isdConfig/batchDelete',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getPermissionListByAppId: {
    url: '/permission/listByAppId',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postCallGetSkillGroupResourceDetail: {
    url: '/monitor/call/getSkillGroupResourceDetail',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getSmartChatAnalysisTaskGetSpecific: {
    url: '/smartChatAnalysisTask/getSpecific',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postTaskCancel: {
    url: '/smartChatAnalysisTask/task/cancel',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getChatAnalysisFilterConfigPage: {
    url: '/isd/chatAnalysisFilterConfig/page',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getChatAnalysisFilterConfigDetail: {
    url: '/isd/chatAnalysisFilterConfig/detail',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postChatAnalysisFilterConfigSave: {
    url: '/isd/chatAnalysisFilterConfig/save',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postChatAnalysisFilterConfigUpdate: {
    url: '/isd/chatAnalysisFilterConfig/update',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postStatusUpdate: {
    url: '/isd/chatAnalysisFilterConfig/status/update',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getTaskExport: {
    url: '/isd/chatAnalysisFilterConfig/task/export',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postOnlineGetOnlineMonitor: {
    url: '/monitor/online/getOnlineMonitor',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getPreviewPlan: {
    url: '/smart/chat/analysis/plan/preview/plan',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getBrainDict: {
    url: '/brain/dict',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getOlConsultMsgGetInConsultOnlineChatRecordResult: {
    url: '/olConsultMsg/getInConsultOnlineChatRecordResult',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getOlConsultMsgGetOfflineConsultOnlineChatRecordResult: {
    url: '/olConsultMsg/getOfflineConsultOnlineChatRecordResult',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postConsulttaskrulePageList: {
    url: '/consulttaskrule/pageList',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getConsulttaskruleDetail: {
    url: '/consulttaskrule/detail',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postConsulttaskruleModify: {
    url: '/consulttaskrule/modify',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postConsulttaskruleSave: {
    url: '/consulttaskrule/save',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postConsulttaskruleDeleteTaskRule: {
    url: '/consulttaskrule/deleteTaskRule',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postExecInTimeTask: {
    url: '/external/smartChatAnalysis/exec/inTimeTask',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postSmartChatAnalysisExecInTimeTask: {
    url: '/external/smartChatAnalysis/execInTimeTask',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postAllSystemAndModuleUpdate: {
    url: '/isdConfig/allSystemAndModule/update',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getAllSystemAndModuleQuery: {
    url: '/isdConfig/allSystemAndModule/query',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postConsulttaskruleMatch: {
    url: '/consulttaskrule/match',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postSaveCheck: {
    url: '/smartChatAnalysisTask/save/check',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getErrorExport: {
    url: '/smartChatAnalysisTask/task/error/export',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getSmartChatAnalysisTaskTestTask: {
    url: '/smartChatAnalysisTask/testTask',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getSmartChatAnalysisTaskGetSummaryConfigFields: {
    url: '/smartChatAnalysisTask/getSummaryConfigFields',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getSummaryMsgId: {
    url: '/smartChatAnalysisTask/summary/msgId',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getAnalysisItem: {
    url: '/smartChatAnalysisTask/summary/analysis/item',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getAnalysisAgent: {
    url: '/smartChatAnalysisTask/summary/analysis/agent',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getAgentItem: {
    url: '/smartChatAnalysisTask/summary/analysis/agent/item',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postResourcePoolUpdateStatus: {
    url: '/resourcePool/updateStatus',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getCommonGetDepartmentAgentList: {
    url: '/common/getDepartmentAgentList',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getListExport: {
    url: '/group/incall/list/export',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getExcelImport: {
    url: '/group/incall/excel/import',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'multipart/form-data' },
  },
  getGroupOnlineListExport: {
    url: '/group/online/list/export',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getGroupOnlineExcelImport: {
    url: '/group/online/excel/import',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'multipart/form-data' },
  },
  postBatchDelete: {
    url: '/group/batch/delete',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getImportTemplate: {
    url: '/group/excel/import/template',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postDeleteCheck: {
    url: '/group/batch/delete/check',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getTodoGetTodoType: {
    url: '/todo/getTodoType',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getTodoGetTodoRole: {
    url: '/todo/getTodoRole',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getPlanGetAnalysisResult: {
    url: '/smart/chat/analysis/plan/getAnalysisResult',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postPlanGetAnalysisResult: {
    url: '/smart/chat/analysis/plan/getAnalysisResult',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postTaskAdd: {
    url: '/ipt/task/add',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postSimpleList: {
    url: '/ipt/task/simple/list',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getTaskTemplate: {
    url: '/ipt/task/template',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postChatMessage: {
    url: '/ipt/trainee/task/case/chat/message',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postCaseDialogue: {
    url: '/ipt/trainee/task/case/dialogue',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getCaseEvaluation: {
    url: '/ipt/trainee/task/case/evaluation',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getCaseStart: {
    url: '/ipt/trainee/task/case/start',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getTaskContinued: {
    url: '/ipt/trainee/task/continued',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getTaskDelete: {
    url: '/ipt/trainee/task/delete',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postTaskList: {
    url: '/ipt/trainee/task/list',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getTaskStart: {
    url: '/ipt/trainee/task/start',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getTaskStop: {
    url: '/ipt/trainee/task/stop',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getTaskView: {
    url: '/ipt/trainee/task/view',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getTaskWelcome: {
    url: '/ipt/trainee/task/welcome',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getResultDownload: {
    url: '/ipt/trainee/task/result/download',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postResultList: {
    url: '/ipt/trainee/task/result/list',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postTaskDelete: {
    url: '/ipt/trainee/task/delete',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getCaseDialogue: {
    url: '/ipt/trainee/task/case/dialogue',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getChatMessage: {
    url: '/ipt/trainee/task/case/chat/message',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postCaseComments: {
    url: '/ipt/trainee/task/case/comments',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  getOrgFindChildrenByParentId: {
    url: '/region/org/findChildrenByParentId',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getOrgGetAllRegionTree: {
    url: '/region/org/getAllRegionTree',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  getOrgGetRegionTreeByCode: {
    url: '/region/org/getRegionTreeByCode',
    method: 'get',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  },
  postOnlineGetOnlineMonitorNoneUser: {
    url: '/monitor/online/getOnlineMonitorNoneUser',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postCommonGetDepartmentAgentList: {
    url: '/common/getDepartmentAgentList',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postCallGetOperatorCallDetail: {
    url: '/monitor/call/getOperatorCallDetail',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postSpecialDayList: {
    url: '/specialDay/list',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
  postWorkTimeList: {
    url: '/workTime/list',
    method: 'post',
    baseURL: '/callcentermanage',
    headers: { 'Content-Type': 'application/json; charset=utf-8' },
  },
};
